apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  type: NodePort
  selector:
    app: client
  ports:
    - name: command
      port: 8080
      targetPort: 8080
      nodePort: 30080
    - name: completion
      port: 8081
      targetPort: 8081
      nodePort: 30081