apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
spec:
  replicas: 3
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: client-image:local
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: METRICS_URL
          value: "http://192.168.64.1:8000/metrics"