apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: server-image:local
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: METRICS_URL
          value: "http://192.168.64.1:8000/metrics"